In [1]:
import pandas as pd

In [2]:
breweries = pd.read_csv("Resources/Clean/texas_breweries.csv")

In [3]:
beers = pd.read_csv("Resources/Clean/texas_beers.csv")

In [4]:
reviews = pd.read_csv("Resources/Clean/texas_reviews.csv")

In [5]:
breweries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 323 entries, 0 to 322
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       323 non-null    int64
 1   name     323 non-null    object
 2   city     323 non-null    object
 3   state    323 non-null    object
 4   country  323 non-null    object
 5   types    323 non-null    object
dtypes: int64(1), object(5)
memory usage: 15.3+ KB

In [6]:
beers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4885 entries, 0 to 4884
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4885 non-null   int64
 1   name          4885 non-null   object
 2   brewery_id    4885 non-null   int64
 3   style         4885 non-null   object
 4   availability  4885 non-null   object
 5   abv           4885 non-null   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 229.1+ KB

In [7]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75417 entries, 0 to 75416
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   beer_id  75417 non-null  int64
 1   look     75417 non-null  float64
 2   smell    75417 non-null  float64
 3   taste    75417 non-null  float64
 4   feel     75417 non-null  float64
 5   overall  75417 non-null  float64
dtypes: float64(5), int64(1)
memory usage: 3.5 MB

In [9]:
merged1 = pd.merge(reviews, beers, left_on='beer_id', right_on='id')
merged1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 75417 entries, 0 to 75416
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   beer_id       75417 non-null  int64
 1   look          75417 non-null  float64
 2   smell         75417 non-null  float64
 3   taste         75417 non-null  float64
 4   feel          75417 non-null  float64
 5   overall       75417 non-null  float64
 6   id            75417 non-null  int64
 7   name          75417 non-null  object
 8   brewery_id    75417 non-null  int64
 9   style         75417 non-null  object
 10  availability  75417 non-null  object
 11  abv           75417 non-null  float64
dtypes: float64(6), int64(3), object(3)
memory usage: 7.5+ MB

In [10]:
merged1 = merged1.drop('id', axis=1)

In [11]:
merged1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 75417 entries, 0 to 75416
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   beer_id       75417 non-null  int64
 1   look          75417 non-null  float64
 2   smell         75417 non-null  float64
 3   taste         75417 non-null  float64
 4   feel          75417 non-null  float64
 5   overall       75417 non-null  float64
 6   name          75417 non-null  object
 7   brewery_id    75417 non-null  int64
 8   style         75417 non-null  object
 9   availability  75417 non-null  object
 10  abv           75417 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 6.9+ MB

In [12]:
merged1.head()

,beer_id,look,smell,taste,feel,overall,name,brewery_id,style,availability,abv
0,203086,3.50,3.50,3.00,3.50,3.25,Hopper House Double IPA,43368,American Imperial IPA,Year-round,8.0
1,203086,2.75,2.75,2.75,2.75,2.75,Hopper House Double IPA,43368,American Imperial IPA,Year-round,8.0
2,203086,3.00,3.00,3.00,3.00,3.00,Hopper House Double IPA,43368,American Imperial IPA,Year-round,8.0
3,203086,3.00,3.00,2.75,2.75,2.75,Hopper House Double IPA,43368,American Imperial IPA,Year-round,8.0
4,203086,4.00,3.50,3.75,3.75,3.75,Hopper House Double IPA,43368,American Imperial IPA,Year-round,8.0

In [13]:
merged1 = merged1.drop('beer_id', axis=1)

In [15]:
merged2 = pd.merge(merged1, breweries, left_on='brewery_id', right_on='id')
merged2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 75417 entries, 0 to 75416
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   look          75417 non-null  float64
 1   smell         75417 non-null  float64
 2   taste         75417 non-null  float64
 3   feel          75417 non-null  float64
 4   overall       75417 non-null  float64
 5   name_x        75417 non-null  object
 6   brewery_id    75417 non-null  int64
 7   style         75417 non-null  object
 8   availability  75417 non-null  object
 9   abv           75417 non-null  float64
 10  id            75417 non-null  int64
 11  name_y        75417 non-null  object
 12  city          75417 non-null  object
 13  state         75417 non-null  object
 14  country       75417 non-null  object
 15  types         75417 non-null  object
dtypes: float64(6), int64(2), object(8)
memory usage: 9.8+ MB

In [16]:
merged2 = merged2.drop('brewery_id', axis=1)

In [17]:
merged2 = merged2.drop('id', axis=1)

In [18]:
merged2.head(20)

,look,smell,taste,feel,overall,name_x,style,availability,abv,name_y,city,state,country,types
0,3.50,3.50,3.00,3.50,3.25,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
1,2.75,2.75,2.75,2.75,2.75,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
2,3.00,3.00,3.00,3.00,3.00,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
3,3.00,3.00,2.75,2.75,2.75,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
4,4.00,3.50,3.75,3.75,3.75,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
5,3.25,3.25,3.25,3.25,3.25,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
6,2.75,2.75,2.75,2.75,2.75,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
7,4.00,3.75,3.50,3.50,3.50,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
8,3.50,3.25,3.50,3.50,3.25,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
9,3.75,4.25,4.00,3.75,4.00,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
10,3.00,3.25,3.25,3.25,3.25,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
11,3.75,3.75,4.00,4.00,4.00,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
12,3.00,3.50,3.25,3.25,3.50,Hopper House Double IPA,American Imperial IPA,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
13,4.25,4.75,4.50,4.25,4.50,Diamonds in my Mouth,New England IPA,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
14,4.25,4.25,4.25,4.25,4.25,Diamonds in my Mouth,New England IPA,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
15,4.25,4.25,4.50,4.25,4.25,Diamonds in my Mouth,New England IPA,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
16,4.50,4.25,4.50,4.25,4.25,Diamonds in my Mouth,New England IPA,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
17,4.00,4.50,4.25,4.25,4.25,Diamonds in my Mouth,New England IPA,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
18,4.25,4.25,4.50,4.50,4.25,Diamonds in my Mouth,New England IPA,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
19,4.00,4.00,3.75,3.75,3.75,Diamonds in my Mouth,New England IPA,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"

In [19]:
merged2 = merged2.rename(columns={'name_x': 'beer_name', 'name_y': 'brewery_name'})

In [20]:
reviews_merged = merged2.reindex(columns=["beer_name", "style", "look", "smell", "taste", "feel", "overall", "availability", "abv", "brewery_name", "city", "state", "country", "types"])
reviews_merged.head(20)

,beer_name,style,look,smell,taste,feel,overall,availability,abv,brewery_name,city,state,country,types
0,Hopper House Double IPA,American Imperial IPA,3.50,3.50,3.00,3.50,3.25,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
1,Hopper House Double IPA,American Imperial IPA,2.75,2.75,2.75,2.75,2.75,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
2,Hopper House Double IPA,American Imperial IPA,3.00,3.00,3.00,3.00,3.00,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
3,Hopper House Double IPA,American Imperial IPA,3.00,3.00,2.75,2.75,2.75,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
4,Hopper House Double IPA,American Imperial IPA,4.00,3.50,3.75,3.75,3.75,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
5,Hopper House Double IPA,American Imperial IPA,3.25,3.25,3.25,3.25,3.25,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
6,Hopper House Double IPA,American Imperial IPA,2.75,2.75,2.75,2.75,2.75,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
7,Hopper House Double IPA,American Imperial IPA,4.00,3.75,3.50,3.50,3.50,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
8,Hopper House Double IPA,American Imperial IPA,3.50,3.25,3.50,3.50,3.25,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
9,Hopper House Double IPA,American Imperial IPA,3.75,4.25,4.00,3.75,4.00,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
10,Hopper House Double IPA,American Imperial IPA,3.00,3.25,3.25,3.25,3.25,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
11,Hopper House Double IPA,American Imperial IPA,3.75,3.75,4.00,4.00,4.00,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
12,Hopper House Double IPA,American Imperial IPA,3.00,3.50,3.25,3.25,3.50,Year-round,8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
13,Diamonds in my Mouth,New England IPA,4.25,4.75,4.50,4.25,4.50,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
14,Diamonds in my Mouth,New England IPA,4.25,4.25,4.25,4.25,4.25,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
15,Diamonds in my Mouth,New England IPA,4.25,4.25,4.50,4.25,4.25,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
16,Diamonds in my Mouth,New England IPA,4.50,4.25,4.50,4.25,4.25,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
17,Diamonds in my Mouth,New England IPA,4.00,4.50,4.25,4.25,4.25,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
18,Diamonds in my Mouth,New England IPA,4.25,4.25,4.50,4.50,4.25,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"
19,Diamonds in my Mouth,New England IPA,4.00,4.00,3.75,3.75,3.75,Limited (brewed once),8.0,Spindletap Brewery,Houston,TX,US,"Brewery, Bar"

In [21]:
reviews_merged.to_csv('Resources/Clean/reviews_merged.csv', index=False)